# Generated by Django 4.0.4 on 2023-06-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('product_name', models.CharField(max_length=50)),
                ('product_url', models.CharField(max_length=1000)),
                ('product_price', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
