# Generated by Django 4.0.4 on 2023-07-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_t', '0002_products_delete_user_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
